development:
  adapter: postgresql
  database: trello_clone_development
  host: localhost
  pool: 5
  
test:
  adapter: postgresql
  database: trello_clone_test
  host: localhost
  pool: 5

# May delete production section... Heroku ignores it
production:
  adapter: postgresql
  database: trello_clone_production
  pool: 5